/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as SignUpSplatRouteImport } from './routes/sign-up.$'
import { Route as SignInSplatRouteImport } from './routes/sign-in.$'
import { Route as AdminStaffRouteImport } from './routes/admin.staff'
import { Route as AdminOrganizationRouteImport } from './routes/admin.organization'
import { Route as TournamentsTournamentIdIndexRouteImport } from './routes/tournaments.$tournamentId.index'
import { Route as TournamentsTournamentIdPlayRouteImport } from './routes/tournaments.$tournamentId.play'
import { Route as AdminTournamentsTournamentIdRouteImport } from './routes/admin.tournaments.$tournamentId'
import { Route as AdminTournamentsTournamentIdIndexRouteImport } from './routes/admin.tournaments.$tournamentId.index'
import { Route as AdminTournamentsTournamentIdStandingsRouteImport } from './routes/admin.tournaments.$tournamentId.standings'
import { Route as AdminTournamentsTournamentIdRegistrationsRouteImport } from './routes/admin.tournaments.$tournamentId.registrations'
import { Route as AdminTournamentsTournamentIdPairingsRouteImport } from './routes/admin.tournaments.$tournamentId.pairings'

const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const SignUpSplatRoute = SignUpSplatRouteImport.update({
  id: '/sign-up/$',
  path: '/sign-up/$',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInSplatRoute = SignInSplatRouteImport.update({
  id: '/sign-in/$',
  path: '/sign-in/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminStaffRoute = AdminStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrganizationRoute = AdminOrganizationRouteImport.update({
  id: '/organization',
  path: '/organization',
  getParentRoute: () => AdminRoute,
} as any)
const TournamentsTournamentIdIndexRoute =
  TournamentsTournamentIdIndexRouteImport.update({
    id: '/tournaments/$tournamentId/',
    path: '/tournaments/$tournamentId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const TournamentsTournamentIdPlayRoute =
  TournamentsTournamentIdPlayRouteImport.update({
    id: '/tournaments/$tournamentId/play',
    path: '/tournaments/$tournamentId/play',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminTournamentsTournamentIdRoute =
  AdminTournamentsTournamentIdRouteImport.update({
    id: '/tournaments/$tournamentId',
    path: '/tournaments/$tournamentId',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminTournamentsTournamentIdIndexRoute =
  AdminTournamentsTournamentIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AdminTournamentsTournamentIdRoute,
  } as any)
const AdminTournamentsTournamentIdStandingsRoute =
  AdminTournamentsTournamentIdStandingsRouteImport.update({
    id: '/standings',
    path: '/standings',
    getParentRoute: () => AdminTournamentsTournamentIdRoute,
  } as any)
const AdminTournamentsTournamentIdRegistrationsRoute =
  AdminTournamentsTournamentIdRegistrationsRouteImport.update({
    id: '/registrations',
    path: '/registrations',
    getParentRoute: () => AdminTournamentsTournamentIdRoute,
  } as any)
const AdminTournamentsTournamentIdPairingsRoute =
  AdminTournamentsTournamentIdPairingsRouteImport.update({
    id: '/pairings',
    path: '/pairings',
    getParentRoute: () => AdminTournamentsTournamentIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/organization': typeof AdminOrganizationRoute
  '/admin/staff': typeof AdminStaffRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/tournaments/$tournamentId': typeof AdminTournamentsTournamentIdRouteWithChildren
  '/tournaments/$tournamentId/play': typeof TournamentsTournamentIdPlayRoute
  '/tournaments/$tournamentId/': typeof TournamentsTournamentIdIndexRoute
  '/admin/tournaments/$tournamentId/pairings': typeof AdminTournamentsTournamentIdPairingsRoute
  '/admin/tournaments/$tournamentId/registrations': typeof AdminTournamentsTournamentIdRegistrationsRoute
  '/admin/tournaments/$tournamentId/standings': typeof AdminTournamentsTournamentIdStandingsRoute
  '/admin/tournaments/$tournamentId/': typeof AdminTournamentsTournamentIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/organization': typeof AdminOrganizationRoute
  '/admin/staff': typeof AdminStaffRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/admin': typeof AdminIndexRoute
  '/tournaments/$tournamentId/play': typeof TournamentsTournamentIdPlayRoute
  '/tournaments/$tournamentId': typeof TournamentsTournamentIdIndexRoute
  '/admin/tournaments/$tournamentId/pairings': typeof AdminTournamentsTournamentIdPairingsRoute
  '/admin/tournaments/$tournamentId/registrations': typeof AdminTournamentsTournamentIdRegistrationsRoute
  '/admin/tournaments/$tournamentId/standings': typeof AdminTournamentsTournamentIdStandingsRoute
  '/admin/tournaments/$tournamentId': typeof AdminTournamentsTournamentIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/organization': typeof AdminOrganizationRoute
  '/admin/staff': typeof AdminStaffRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/tournaments/$tournamentId': typeof AdminTournamentsTournamentIdRouteWithChildren
  '/tournaments/$tournamentId/play': typeof TournamentsTournamentIdPlayRoute
  '/tournaments/$tournamentId/': typeof TournamentsTournamentIdIndexRoute
  '/admin/tournaments/$tournamentId/pairings': typeof AdminTournamentsTournamentIdPairingsRoute
  '/admin/tournaments/$tournamentId/registrations': typeof AdminTournamentsTournamentIdRegistrationsRoute
  '/admin/tournaments/$tournamentId/standings': typeof AdminTournamentsTournamentIdStandingsRoute
  '/admin/tournaments/$tournamentId/': typeof AdminTournamentsTournamentIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin/organization'
    | '/admin/staff'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/admin/'
    | '/admin/tournaments/$tournamentId'
    | '/tournaments/$tournamentId/play'
    | '/tournaments/$tournamentId/'
    | '/admin/tournaments/$tournamentId/pairings'
    | '/admin/tournaments/$tournamentId/registrations'
    | '/admin/tournaments/$tournamentId/standings'
    | '/admin/tournaments/$tournamentId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/organization'
    | '/admin/staff'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/admin'
    | '/tournaments/$tournamentId/play'
    | '/tournaments/$tournamentId'
    | '/admin/tournaments/$tournamentId/pairings'
    | '/admin/tournaments/$tournamentId/registrations'
    | '/admin/tournaments/$tournamentId/standings'
    | '/admin/tournaments/$tournamentId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/admin/organization'
    | '/admin/staff'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/admin/'
    | '/admin/tournaments/$tournamentId'
    | '/tournaments/$tournamentId/play'
    | '/tournaments/$tournamentId/'
    | '/admin/tournaments/$tournamentId/pairings'
    | '/admin/tournaments/$tournamentId/registrations'
    | '/admin/tournaments/$tournamentId/standings'
    | '/admin/tournaments/$tournamentId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  SignInSplatRoute: typeof SignInSplatRoute
  SignUpSplatRoute: typeof SignUpSplatRoute
  TournamentsTournamentIdPlayRoute: typeof TournamentsTournamentIdPlayRoute
  TournamentsTournamentIdIndexRoute: typeof TournamentsTournamentIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/sign-up/$': {
      id: '/sign-up/$'
      path: '/sign-up/$'
      fullPath: '/sign-up/$'
      preLoaderRoute: typeof SignUpSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in/$': {
      id: '/sign-in/$'
      path: '/sign-in/$'
      fullPath: '/sign-in/$'
      preLoaderRoute: typeof SignInSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/staff': {
      id: '/admin/staff'
      path: '/staff'
      fullPath: '/admin/staff'
      preLoaderRoute: typeof AdminStaffRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/organization': {
      id: '/admin/organization'
      path: '/organization'
      fullPath: '/admin/organization'
      preLoaderRoute: typeof AdminOrganizationRouteImport
      parentRoute: typeof AdminRoute
    }
    '/tournaments/$tournamentId/': {
      id: '/tournaments/$tournamentId/'
      path: '/tournaments/$tournamentId'
      fullPath: '/tournaments/$tournamentId/'
      preLoaderRoute: typeof TournamentsTournamentIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tournaments/$tournamentId/play': {
      id: '/tournaments/$tournamentId/play'
      path: '/tournaments/$tournamentId/play'
      fullPath: '/tournaments/$tournamentId/play'
      preLoaderRoute: typeof TournamentsTournamentIdPlayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/tournaments/$tournamentId': {
      id: '/admin/tournaments/$tournamentId'
      path: '/tournaments/$tournamentId'
      fullPath: '/admin/tournaments/$tournamentId'
      preLoaderRoute: typeof AdminTournamentsTournamentIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/tournaments/$tournamentId/': {
      id: '/admin/tournaments/$tournamentId/'
      path: '/'
      fullPath: '/admin/tournaments/$tournamentId/'
      preLoaderRoute: typeof AdminTournamentsTournamentIdIndexRouteImport
      parentRoute: typeof AdminTournamentsTournamentIdRoute
    }
    '/admin/tournaments/$tournamentId/standings': {
      id: '/admin/tournaments/$tournamentId/standings'
      path: '/standings'
      fullPath: '/admin/tournaments/$tournamentId/standings'
      preLoaderRoute: typeof AdminTournamentsTournamentIdStandingsRouteImport
      parentRoute: typeof AdminTournamentsTournamentIdRoute
    }
    '/admin/tournaments/$tournamentId/registrations': {
      id: '/admin/tournaments/$tournamentId/registrations'
      path: '/registrations'
      fullPath: '/admin/tournaments/$tournamentId/registrations'
      preLoaderRoute: typeof AdminTournamentsTournamentIdRegistrationsRouteImport
      parentRoute: typeof AdminTournamentsTournamentIdRoute
    }
    '/admin/tournaments/$tournamentId/pairings': {
      id: '/admin/tournaments/$tournamentId/pairings'
      path: '/pairings'
      fullPath: '/admin/tournaments/$tournamentId/pairings'
      preLoaderRoute: typeof AdminTournamentsTournamentIdPairingsRouteImport
      parentRoute: typeof AdminTournamentsTournamentIdRoute
    }
  }
}

interface AdminTournamentsTournamentIdRouteChildren {
  AdminTournamentsTournamentIdPairingsRoute: typeof AdminTournamentsTournamentIdPairingsRoute
  AdminTournamentsTournamentIdRegistrationsRoute: typeof AdminTournamentsTournamentIdRegistrationsRoute
  AdminTournamentsTournamentIdStandingsRoute: typeof AdminTournamentsTournamentIdStandingsRoute
  AdminTournamentsTournamentIdIndexRoute: typeof AdminTournamentsTournamentIdIndexRoute
}

const AdminTournamentsTournamentIdRouteChildren: AdminTournamentsTournamentIdRouteChildren =
  {
    AdminTournamentsTournamentIdPairingsRoute:
      AdminTournamentsTournamentIdPairingsRoute,
    AdminTournamentsTournamentIdRegistrationsRoute:
      AdminTournamentsTournamentIdRegistrationsRoute,
    AdminTournamentsTournamentIdStandingsRoute:
      AdminTournamentsTournamentIdStandingsRoute,
    AdminTournamentsTournamentIdIndexRoute:
      AdminTournamentsTournamentIdIndexRoute,
  }

const AdminTournamentsTournamentIdRouteWithChildren =
  AdminTournamentsTournamentIdRoute._addFileChildren(
    AdminTournamentsTournamentIdRouteChildren,
  )

interface AdminRouteChildren {
  AdminOrganizationRoute: typeof AdminOrganizationRoute
  AdminStaffRoute: typeof AdminStaffRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminTournamentsTournamentIdRoute: typeof AdminTournamentsTournamentIdRouteWithChildren
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminOrganizationRoute: AdminOrganizationRoute,
  AdminStaffRoute: AdminStaffRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminTournamentsTournamentIdRoute:
    AdminTournamentsTournamentIdRouteWithChildren,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  SignInSplatRoute: SignInSplatRoute,
  SignUpSplatRoute: SignUpSplatRoute,
  TournamentsTournamentIdPlayRoute: TournamentsTournamentIdPlayRoute,
  TournamentsTournamentIdIndexRoute: TournamentsTournamentIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
