/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as UsersPublicCodeRouteImport } from './routes/users.$publicCode'
import { Route as SignUpSplatRouteImport } from './routes/sign-up.$'
import { Route as SignInSplatRouteImport } from './routes/sign-in.$'
import { Route as JoinInviteCodeRouteImport } from './routes/join.$inviteCode'
import { Route as AdminStripeReturnRouteImport } from './routes/admin.stripe-return'
import { Route as AdminStaffRouteImport } from './routes/admin.staff'
import { Route as AdminOrganizationRouteImport } from './routes/admin.organization'
import { Route as TournamentsTournamentIdIndexRouteImport } from './routes/tournaments.$tournamentId.index'
import { Route as ConventionsConventionIdIndexRouteImport } from './routes/conventions.$conventionId.index'
import { Route as AdminConventionsIndexRouteImport } from './routes/admin.conventions.index'
import { Route as TournamentsTournamentIdPlayRouteImport } from './routes/tournaments.$tournamentId.play'
import { Route as TournamentsTournamentIdPaymentRouteImport } from './routes/tournaments.$tournamentId.payment'
import { Route as TournamentsTournamentIdDecklistRouteImport } from './routes/tournaments.$tournamentId.decklist'
import { Route as ConventionsConventionIdPaymentRouteImport } from './routes/conventions.$conventionId.payment'
import { Route as AdminTournamentsTournamentIdRouteImport } from './routes/admin.tournaments.$tournamentId'
import { Route as AdminConventionsConventionIdRouteImport } from './routes/admin.conventions.$conventionId'
import { Route as AdminTournamentsTournamentIdIndexRouteImport } from './routes/admin.tournaments.$tournamentId.index'
import { Route as AdminConventionsConventionIdIndexRouteImport } from './routes/admin.conventions.$conventionId.index'
import { Route as AdminTournamentsTournamentIdTimerRouteImport } from './routes/admin.tournaments.$tournamentId.timer'
import { Route as AdminTournamentsTournamentIdStandingsRouteImport } from './routes/admin.tournaments.$tournamentId.standings'
import { Route as AdminTournamentsTournamentIdSettingsRouteImport } from './routes/admin.tournaments.$tournamentId.settings'
import { Route as AdminTournamentsTournamentIdRegistrationsRouteImport } from './routes/admin.tournaments.$tournamentId.registrations'
import { Route as AdminTournamentsTournamentIdPairingsRouteImport } from './routes/admin.tournaments.$tournamentId.pairings'
import { Route as AdminTournamentsTournamentIdLogRouteImport } from './routes/admin.tournaments.$tournamentId.log'
import { Route as AdminConventionsConventionIdSettingsRouteImport } from './routes/admin.conventions.$conventionId.settings'
import { Route as AdminConventionsConventionIdRegistrationsRouteImport } from './routes/admin.conventions.$conventionId.registrations'
import { Route as AdminConventionsConventionIdLogRouteImport } from './routes/admin.conventions.$conventionId.log'
import { Route as AdminConventionsConventionIdEventsRouteImport } from './routes/admin.conventions.$conventionId.events'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const UsersPublicCodeRoute = UsersPublicCodeRouteImport.update({
  id: '/users/$publicCode',
  path: '/users/$publicCode',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpSplatRoute = SignUpSplatRouteImport.update({
  id: '/sign-up/$',
  path: '/sign-up/$',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInSplatRoute = SignInSplatRouteImport.update({
  id: '/sign-in/$',
  path: '/sign-in/$',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinInviteCodeRoute = JoinInviteCodeRouteImport.update({
  id: '/join/$inviteCode',
  path: '/join/$inviteCode',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminStripeReturnRoute = AdminStripeReturnRouteImport.update({
  id: '/stripe-return',
  path: '/stripe-return',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStaffRoute = AdminStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrganizationRoute = AdminOrganizationRouteImport.update({
  id: '/organization',
  path: '/organization',
  getParentRoute: () => AdminRoute,
} as any)
const TournamentsTournamentIdIndexRoute =
  TournamentsTournamentIdIndexRouteImport.update({
    id: '/tournaments/$tournamentId/',
    path: '/tournaments/$tournamentId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ConventionsConventionIdIndexRoute =
  ConventionsConventionIdIndexRouteImport.update({
    id: '/conventions/$conventionId/',
    path: '/conventions/$conventionId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminConventionsIndexRoute = AdminConventionsIndexRouteImport.update({
  id: '/conventions/',
  path: '/conventions/',
  getParentRoute: () => AdminRoute,
} as any)
const TournamentsTournamentIdPlayRoute =
  TournamentsTournamentIdPlayRouteImport.update({
    id: '/tournaments/$tournamentId/play',
    path: '/tournaments/$tournamentId/play',
    getParentRoute: () => rootRouteImport,
  } as any)
const TournamentsTournamentIdPaymentRoute =
  TournamentsTournamentIdPaymentRouteImport.update({
    id: '/tournaments/$tournamentId/payment',
    path: '/tournaments/$tournamentId/payment',
    getParentRoute: () => rootRouteImport,
  } as any)
const TournamentsTournamentIdDecklistRoute =
  TournamentsTournamentIdDecklistRouteImport.update({
    id: '/tournaments/$tournamentId/decklist',
    path: '/tournaments/$tournamentId/decklist',
    getParentRoute: () => rootRouteImport,
  } as any)
const ConventionsConventionIdPaymentRoute =
  ConventionsConventionIdPaymentRouteImport.update({
    id: '/conventions/$conventionId/payment',
    path: '/conventions/$conventionId/payment',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminTournamentsTournamentIdRoute =
  AdminTournamentsTournamentIdRouteImport.update({
    id: '/tournaments/$tournamentId',
    path: '/tournaments/$tournamentId',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminConventionsConventionIdRoute =
  AdminConventionsConventionIdRouteImport.update({
    id: '/conventions/$conventionId',
    path: '/conventions/$conventionId',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminTournamentsTournamentIdIndexRoute =
  AdminTournamentsTournamentIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AdminTournamentsTournamentIdRoute,
  } as any)
const AdminConventionsConventionIdIndexRoute =
  AdminConventionsConventionIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AdminConventionsConventionIdRoute,
  } as any)
const AdminTournamentsTournamentIdTimerRoute =
  AdminTournamentsTournamentIdTimerRouteImport.update({
    id: '/timer',
    path: '/timer',
    getParentRoute: () => AdminTournamentsTournamentIdRoute,
  } as any)
const AdminTournamentsTournamentIdStandingsRoute =
  AdminTournamentsTournamentIdStandingsRouteImport.update({
    id: '/standings',
    path: '/standings',
    getParentRoute: () => AdminTournamentsTournamentIdRoute,
  } as any)
const AdminTournamentsTournamentIdSettingsRoute =
  AdminTournamentsTournamentIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AdminTournamentsTournamentIdRoute,
  } as any)
const AdminTournamentsTournamentIdRegistrationsRoute =
  AdminTournamentsTournamentIdRegistrationsRouteImport.update({
    id: '/registrations',
    path: '/registrations',
    getParentRoute: () => AdminTournamentsTournamentIdRoute,
  } as any)
const AdminTournamentsTournamentIdPairingsRoute =
  AdminTournamentsTournamentIdPairingsRouteImport.update({
    id: '/pairings',
    path: '/pairings',
    getParentRoute: () => AdminTournamentsTournamentIdRoute,
  } as any)
const AdminTournamentsTournamentIdLogRoute =
  AdminTournamentsTournamentIdLogRouteImport.update({
    id: '/log',
    path: '/log',
    getParentRoute: () => AdminTournamentsTournamentIdRoute,
  } as any)
const AdminConventionsConventionIdSettingsRoute =
  AdminConventionsConventionIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AdminConventionsConventionIdRoute,
  } as any)
const AdminConventionsConventionIdRegistrationsRoute =
  AdminConventionsConventionIdRegistrationsRouteImport.update({
    id: '/registrations',
    path: '/registrations',
    getParentRoute: () => AdminConventionsConventionIdRoute,
  } as any)
const AdminConventionsConventionIdLogRoute =
  AdminConventionsConventionIdLogRouteImport.update({
    id: '/log',
    path: '/log',
    getParentRoute: () => AdminConventionsConventionIdRoute,
  } as any)
const AdminConventionsConventionIdEventsRoute =
  AdminConventionsConventionIdEventsRouteImport.update({
    id: '/events',
    path: '/events',
    getParentRoute: () => AdminConventionsConventionIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/settings': typeof SettingsRoute
  '/admin/organization': typeof AdminOrganizationRoute
  '/admin/staff': typeof AdminStaffRoute
  '/admin/stripe-return': typeof AdminStripeReturnRoute
  '/join/$inviteCode': typeof JoinInviteCodeRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/users/$publicCode': typeof UsersPublicCodeRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/conventions/$conventionId': typeof AdminConventionsConventionIdRouteWithChildren
  '/admin/tournaments/$tournamentId': typeof AdminTournamentsTournamentIdRouteWithChildren
  '/conventions/$conventionId/payment': typeof ConventionsConventionIdPaymentRoute
  '/tournaments/$tournamentId/decklist': typeof TournamentsTournamentIdDecklistRoute
  '/tournaments/$tournamentId/payment': typeof TournamentsTournamentIdPaymentRoute
  '/tournaments/$tournamentId/play': typeof TournamentsTournamentIdPlayRoute
  '/admin/conventions/': typeof AdminConventionsIndexRoute
  '/conventions/$conventionId/': typeof ConventionsConventionIdIndexRoute
  '/tournaments/$tournamentId/': typeof TournamentsTournamentIdIndexRoute
  '/admin/conventions/$conventionId/events': typeof AdminConventionsConventionIdEventsRoute
  '/admin/conventions/$conventionId/log': typeof AdminConventionsConventionIdLogRoute
  '/admin/conventions/$conventionId/registrations': typeof AdminConventionsConventionIdRegistrationsRoute
  '/admin/conventions/$conventionId/settings': typeof AdminConventionsConventionIdSettingsRoute
  '/admin/tournaments/$tournamentId/log': typeof AdminTournamentsTournamentIdLogRoute
  '/admin/tournaments/$tournamentId/pairings': typeof AdminTournamentsTournamentIdPairingsRoute
  '/admin/tournaments/$tournamentId/registrations': typeof AdminTournamentsTournamentIdRegistrationsRoute
  '/admin/tournaments/$tournamentId/settings': typeof AdminTournamentsTournamentIdSettingsRoute
  '/admin/tournaments/$tournamentId/standings': typeof AdminTournamentsTournamentIdStandingsRoute
  '/admin/tournaments/$tournamentId/timer': typeof AdminTournamentsTournamentIdTimerRoute
  '/admin/conventions/$conventionId/': typeof AdminConventionsConventionIdIndexRoute
  '/admin/tournaments/$tournamentId/': typeof AdminTournamentsTournamentIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/admin/organization': typeof AdminOrganizationRoute
  '/admin/staff': typeof AdminStaffRoute
  '/admin/stripe-return': typeof AdminStripeReturnRoute
  '/join/$inviteCode': typeof JoinInviteCodeRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/users/$publicCode': typeof UsersPublicCodeRoute
  '/admin': typeof AdminIndexRoute
  '/conventions/$conventionId/payment': typeof ConventionsConventionIdPaymentRoute
  '/tournaments/$tournamentId/decklist': typeof TournamentsTournamentIdDecklistRoute
  '/tournaments/$tournamentId/payment': typeof TournamentsTournamentIdPaymentRoute
  '/tournaments/$tournamentId/play': typeof TournamentsTournamentIdPlayRoute
  '/admin/conventions': typeof AdminConventionsIndexRoute
  '/conventions/$conventionId': typeof ConventionsConventionIdIndexRoute
  '/tournaments/$tournamentId': typeof TournamentsTournamentIdIndexRoute
  '/admin/conventions/$conventionId/events': typeof AdminConventionsConventionIdEventsRoute
  '/admin/conventions/$conventionId/log': typeof AdminConventionsConventionIdLogRoute
  '/admin/conventions/$conventionId/registrations': typeof AdminConventionsConventionIdRegistrationsRoute
  '/admin/conventions/$conventionId/settings': typeof AdminConventionsConventionIdSettingsRoute
  '/admin/tournaments/$tournamentId/log': typeof AdminTournamentsTournamentIdLogRoute
  '/admin/tournaments/$tournamentId/pairings': typeof AdminTournamentsTournamentIdPairingsRoute
  '/admin/tournaments/$tournamentId/registrations': typeof AdminTournamentsTournamentIdRegistrationsRoute
  '/admin/tournaments/$tournamentId/settings': typeof AdminTournamentsTournamentIdSettingsRoute
  '/admin/tournaments/$tournamentId/standings': typeof AdminTournamentsTournamentIdStandingsRoute
  '/admin/tournaments/$tournamentId/timer': typeof AdminTournamentsTournamentIdTimerRoute
  '/admin/conventions/$conventionId': typeof AdminConventionsConventionIdIndexRoute
  '/admin/tournaments/$tournamentId': typeof AdminTournamentsTournamentIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/settings': typeof SettingsRoute
  '/admin/organization': typeof AdminOrganizationRoute
  '/admin/staff': typeof AdminStaffRoute
  '/admin/stripe-return': typeof AdminStripeReturnRoute
  '/join/$inviteCode': typeof JoinInviteCodeRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/users/$publicCode': typeof UsersPublicCodeRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/conventions/$conventionId': typeof AdminConventionsConventionIdRouteWithChildren
  '/admin/tournaments/$tournamentId': typeof AdminTournamentsTournamentIdRouteWithChildren
  '/conventions/$conventionId/payment': typeof ConventionsConventionIdPaymentRoute
  '/tournaments/$tournamentId/decklist': typeof TournamentsTournamentIdDecklistRoute
  '/tournaments/$tournamentId/payment': typeof TournamentsTournamentIdPaymentRoute
  '/tournaments/$tournamentId/play': typeof TournamentsTournamentIdPlayRoute
  '/admin/conventions/': typeof AdminConventionsIndexRoute
  '/conventions/$conventionId/': typeof ConventionsConventionIdIndexRoute
  '/tournaments/$tournamentId/': typeof TournamentsTournamentIdIndexRoute
  '/admin/conventions/$conventionId/events': typeof AdminConventionsConventionIdEventsRoute
  '/admin/conventions/$conventionId/log': typeof AdminConventionsConventionIdLogRoute
  '/admin/conventions/$conventionId/registrations': typeof AdminConventionsConventionIdRegistrationsRoute
  '/admin/conventions/$conventionId/settings': typeof AdminConventionsConventionIdSettingsRoute
  '/admin/tournaments/$tournamentId/log': typeof AdminTournamentsTournamentIdLogRoute
  '/admin/tournaments/$tournamentId/pairings': typeof AdminTournamentsTournamentIdPairingsRoute
  '/admin/tournaments/$tournamentId/registrations': typeof AdminTournamentsTournamentIdRegistrationsRoute
  '/admin/tournaments/$tournamentId/settings': typeof AdminTournamentsTournamentIdSettingsRoute
  '/admin/tournaments/$tournamentId/standings': typeof AdminTournamentsTournamentIdStandingsRoute
  '/admin/tournaments/$tournamentId/timer': typeof AdminTournamentsTournamentIdTimerRoute
  '/admin/conventions/$conventionId/': typeof AdminConventionsConventionIdIndexRoute
  '/admin/tournaments/$tournamentId/': typeof AdminTournamentsTournamentIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/settings'
    | '/admin/organization'
    | '/admin/staff'
    | '/admin/stripe-return'
    | '/join/$inviteCode'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/users/$publicCode'
    | '/admin/'
    | '/admin/conventions/$conventionId'
    | '/admin/tournaments/$tournamentId'
    | '/conventions/$conventionId/payment'
    | '/tournaments/$tournamentId/decklist'
    | '/tournaments/$tournamentId/payment'
    | '/tournaments/$tournamentId/play'
    | '/admin/conventions/'
    | '/conventions/$conventionId/'
    | '/tournaments/$tournamentId/'
    | '/admin/conventions/$conventionId/events'
    | '/admin/conventions/$conventionId/log'
    | '/admin/conventions/$conventionId/registrations'
    | '/admin/conventions/$conventionId/settings'
    | '/admin/tournaments/$tournamentId/log'
    | '/admin/tournaments/$tournamentId/pairings'
    | '/admin/tournaments/$tournamentId/registrations'
    | '/admin/tournaments/$tournamentId/settings'
    | '/admin/tournaments/$tournamentId/standings'
    | '/admin/tournaments/$tournamentId/timer'
    | '/admin/conventions/$conventionId/'
    | '/admin/tournaments/$tournamentId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/settings'
    | '/admin/organization'
    | '/admin/staff'
    | '/admin/stripe-return'
    | '/join/$inviteCode'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/users/$publicCode'
    | '/admin'
    | '/conventions/$conventionId/payment'
    | '/tournaments/$tournamentId/decklist'
    | '/tournaments/$tournamentId/payment'
    | '/tournaments/$tournamentId/play'
    | '/admin/conventions'
    | '/conventions/$conventionId'
    | '/tournaments/$tournamentId'
    | '/admin/conventions/$conventionId/events'
    | '/admin/conventions/$conventionId/log'
    | '/admin/conventions/$conventionId/registrations'
    | '/admin/conventions/$conventionId/settings'
    | '/admin/tournaments/$tournamentId/log'
    | '/admin/tournaments/$tournamentId/pairings'
    | '/admin/tournaments/$tournamentId/registrations'
    | '/admin/tournaments/$tournamentId/settings'
    | '/admin/tournaments/$tournamentId/standings'
    | '/admin/tournaments/$tournamentId/timer'
    | '/admin/conventions/$conventionId'
    | '/admin/tournaments/$tournamentId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/settings'
    | '/admin/organization'
    | '/admin/staff'
    | '/admin/stripe-return'
    | '/join/$inviteCode'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/users/$publicCode'
    | '/admin/'
    | '/admin/conventions/$conventionId'
    | '/admin/tournaments/$tournamentId'
    | '/conventions/$conventionId/payment'
    | '/tournaments/$tournamentId/decklist'
    | '/tournaments/$tournamentId/payment'
    | '/tournaments/$tournamentId/play'
    | '/admin/conventions/'
    | '/conventions/$conventionId/'
    | '/tournaments/$tournamentId/'
    | '/admin/conventions/$conventionId/events'
    | '/admin/conventions/$conventionId/log'
    | '/admin/conventions/$conventionId/registrations'
    | '/admin/conventions/$conventionId/settings'
    | '/admin/tournaments/$tournamentId/log'
    | '/admin/tournaments/$tournamentId/pairings'
    | '/admin/tournaments/$tournamentId/registrations'
    | '/admin/tournaments/$tournamentId/settings'
    | '/admin/tournaments/$tournamentId/standings'
    | '/admin/tournaments/$tournamentId/timer'
    | '/admin/conventions/$conventionId/'
    | '/admin/tournaments/$tournamentId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  SettingsRoute: typeof SettingsRoute
  JoinInviteCodeRoute: typeof JoinInviteCodeRoute
  SignInSplatRoute: typeof SignInSplatRoute
  SignUpSplatRoute: typeof SignUpSplatRoute
  UsersPublicCodeRoute: typeof UsersPublicCodeRoute
  ConventionsConventionIdPaymentRoute: typeof ConventionsConventionIdPaymentRoute
  TournamentsTournamentIdDecklistRoute: typeof TournamentsTournamentIdDecklistRoute
  TournamentsTournamentIdPaymentRoute: typeof TournamentsTournamentIdPaymentRoute
  TournamentsTournamentIdPlayRoute: typeof TournamentsTournamentIdPlayRoute
  ConventionsConventionIdIndexRoute: typeof ConventionsConventionIdIndexRoute
  TournamentsTournamentIdIndexRoute: typeof TournamentsTournamentIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/users/$publicCode': {
      id: '/users/$publicCode'
      path: '/users/$publicCode'
      fullPath: '/users/$publicCode'
      preLoaderRoute: typeof UsersPublicCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up/$': {
      id: '/sign-up/$'
      path: '/sign-up/$'
      fullPath: '/sign-up/$'
      preLoaderRoute: typeof SignUpSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in/$': {
      id: '/sign-in/$'
      path: '/sign-in/$'
      fullPath: '/sign-in/$'
      preLoaderRoute: typeof SignInSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join/$inviteCode': {
      id: '/join/$inviteCode'
      path: '/join/$inviteCode'
      fullPath: '/join/$inviteCode'
      preLoaderRoute: typeof JoinInviteCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/stripe-return': {
      id: '/admin/stripe-return'
      path: '/stripe-return'
      fullPath: '/admin/stripe-return'
      preLoaderRoute: typeof AdminStripeReturnRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/staff': {
      id: '/admin/staff'
      path: '/staff'
      fullPath: '/admin/staff'
      preLoaderRoute: typeof AdminStaffRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/organization': {
      id: '/admin/organization'
      path: '/organization'
      fullPath: '/admin/organization'
      preLoaderRoute: typeof AdminOrganizationRouteImport
      parentRoute: typeof AdminRoute
    }
    '/tournaments/$tournamentId/': {
      id: '/tournaments/$tournamentId/'
      path: '/tournaments/$tournamentId'
      fullPath: '/tournaments/$tournamentId/'
      preLoaderRoute: typeof TournamentsTournamentIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conventions/$conventionId/': {
      id: '/conventions/$conventionId/'
      path: '/conventions/$conventionId'
      fullPath: '/conventions/$conventionId/'
      preLoaderRoute: typeof ConventionsConventionIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/conventions/': {
      id: '/admin/conventions/'
      path: '/conventions'
      fullPath: '/admin/conventions/'
      preLoaderRoute: typeof AdminConventionsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/tournaments/$tournamentId/play': {
      id: '/tournaments/$tournamentId/play'
      path: '/tournaments/$tournamentId/play'
      fullPath: '/tournaments/$tournamentId/play'
      preLoaderRoute: typeof TournamentsTournamentIdPlayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tournaments/$tournamentId/payment': {
      id: '/tournaments/$tournamentId/payment'
      path: '/tournaments/$tournamentId/payment'
      fullPath: '/tournaments/$tournamentId/payment'
      preLoaderRoute: typeof TournamentsTournamentIdPaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tournaments/$tournamentId/decklist': {
      id: '/tournaments/$tournamentId/decklist'
      path: '/tournaments/$tournamentId/decklist'
      fullPath: '/tournaments/$tournamentId/decklist'
      preLoaderRoute: typeof TournamentsTournamentIdDecklistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conventions/$conventionId/payment': {
      id: '/conventions/$conventionId/payment'
      path: '/conventions/$conventionId/payment'
      fullPath: '/conventions/$conventionId/payment'
      preLoaderRoute: typeof ConventionsConventionIdPaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/tournaments/$tournamentId': {
      id: '/admin/tournaments/$tournamentId'
      path: '/tournaments/$tournamentId'
      fullPath: '/admin/tournaments/$tournamentId'
      preLoaderRoute: typeof AdminTournamentsTournamentIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/conventions/$conventionId': {
      id: '/admin/conventions/$conventionId'
      path: '/conventions/$conventionId'
      fullPath: '/admin/conventions/$conventionId'
      preLoaderRoute: typeof AdminConventionsConventionIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/tournaments/$tournamentId/': {
      id: '/admin/tournaments/$tournamentId/'
      path: '/'
      fullPath: '/admin/tournaments/$tournamentId/'
      preLoaderRoute: typeof AdminTournamentsTournamentIdIndexRouteImport
      parentRoute: typeof AdminTournamentsTournamentIdRoute
    }
    '/admin/conventions/$conventionId/': {
      id: '/admin/conventions/$conventionId/'
      path: '/'
      fullPath: '/admin/conventions/$conventionId/'
      preLoaderRoute: typeof AdminConventionsConventionIdIndexRouteImport
      parentRoute: typeof AdminConventionsConventionIdRoute
    }
    '/admin/tournaments/$tournamentId/timer': {
      id: '/admin/tournaments/$tournamentId/timer'
      path: '/timer'
      fullPath: '/admin/tournaments/$tournamentId/timer'
      preLoaderRoute: typeof AdminTournamentsTournamentIdTimerRouteImport
      parentRoute: typeof AdminTournamentsTournamentIdRoute
    }
    '/admin/tournaments/$tournamentId/standings': {
      id: '/admin/tournaments/$tournamentId/standings'
      path: '/standings'
      fullPath: '/admin/tournaments/$tournamentId/standings'
      preLoaderRoute: typeof AdminTournamentsTournamentIdStandingsRouteImport
      parentRoute: typeof AdminTournamentsTournamentIdRoute
    }
    '/admin/tournaments/$tournamentId/settings': {
      id: '/admin/tournaments/$tournamentId/settings'
      path: '/settings'
      fullPath: '/admin/tournaments/$tournamentId/settings'
      preLoaderRoute: typeof AdminTournamentsTournamentIdSettingsRouteImport
      parentRoute: typeof AdminTournamentsTournamentIdRoute
    }
    '/admin/tournaments/$tournamentId/registrations': {
      id: '/admin/tournaments/$tournamentId/registrations'
      path: '/registrations'
      fullPath: '/admin/tournaments/$tournamentId/registrations'
      preLoaderRoute: typeof AdminTournamentsTournamentIdRegistrationsRouteImport
      parentRoute: typeof AdminTournamentsTournamentIdRoute
    }
    '/admin/tournaments/$tournamentId/pairings': {
      id: '/admin/tournaments/$tournamentId/pairings'
      path: '/pairings'
      fullPath: '/admin/tournaments/$tournamentId/pairings'
      preLoaderRoute: typeof AdminTournamentsTournamentIdPairingsRouteImport
      parentRoute: typeof AdminTournamentsTournamentIdRoute
    }
    '/admin/tournaments/$tournamentId/log': {
      id: '/admin/tournaments/$tournamentId/log'
      path: '/log'
      fullPath: '/admin/tournaments/$tournamentId/log'
      preLoaderRoute: typeof AdminTournamentsTournamentIdLogRouteImport
      parentRoute: typeof AdminTournamentsTournamentIdRoute
    }
    '/admin/conventions/$conventionId/settings': {
      id: '/admin/conventions/$conventionId/settings'
      path: '/settings'
      fullPath: '/admin/conventions/$conventionId/settings'
      preLoaderRoute: typeof AdminConventionsConventionIdSettingsRouteImport
      parentRoute: typeof AdminConventionsConventionIdRoute
    }
    '/admin/conventions/$conventionId/registrations': {
      id: '/admin/conventions/$conventionId/registrations'
      path: '/registrations'
      fullPath: '/admin/conventions/$conventionId/registrations'
      preLoaderRoute: typeof AdminConventionsConventionIdRegistrationsRouteImport
      parentRoute: typeof AdminConventionsConventionIdRoute
    }
    '/admin/conventions/$conventionId/log': {
      id: '/admin/conventions/$conventionId/log'
      path: '/log'
      fullPath: '/admin/conventions/$conventionId/log'
      preLoaderRoute: typeof AdminConventionsConventionIdLogRouteImport
      parentRoute: typeof AdminConventionsConventionIdRoute
    }
    '/admin/conventions/$conventionId/events': {
      id: '/admin/conventions/$conventionId/events'
      path: '/events'
      fullPath: '/admin/conventions/$conventionId/events'
      preLoaderRoute: typeof AdminConventionsConventionIdEventsRouteImport
      parentRoute: typeof AdminConventionsConventionIdRoute
    }
  }
}

interface AdminConventionsConventionIdRouteChildren {
  AdminConventionsConventionIdEventsRoute: typeof AdminConventionsConventionIdEventsRoute
  AdminConventionsConventionIdLogRoute: typeof AdminConventionsConventionIdLogRoute
  AdminConventionsConventionIdRegistrationsRoute: typeof AdminConventionsConventionIdRegistrationsRoute
  AdminConventionsConventionIdSettingsRoute: typeof AdminConventionsConventionIdSettingsRoute
  AdminConventionsConventionIdIndexRoute: typeof AdminConventionsConventionIdIndexRoute
}

const AdminConventionsConventionIdRouteChildren: AdminConventionsConventionIdRouteChildren =
  {
    AdminConventionsConventionIdEventsRoute:
      AdminConventionsConventionIdEventsRoute,
    AdminConventionsConventionIdLogRoute: AdminConventionsConventionIdLogRoute,
    AdminConventionsConventionIdRegistrationsRoute:
      AdminConventionsConventionIdRegistrationsRoute,
    AdminConventionsConventionIdSettingsRoute:
      AdminConventionsConventionIdSettingsRoute,
    AdminConventionsConventionIdIndexRoute:
      AdminConventionsConventionIdIndexRoute,
  }

const AdminConventionsConventionIdRouteWithChildren =
  AdminConventionsConventionIdRoute._addFileChildren(
    AdminConventionsConventionIdRouteChildren,
  )

interface AdminTournamentsTournamentIdRouteChildren {
  AdminTournamentsTournamentIdLogRoute: typeof AdminTournamentsTournamentIdLogRoute
  AdminTournamentsTournamentIdPairingsRoute: typeof AdminTournamentsTournamentIdPairingsRoute
  AdminTournamentsTournamentIdRegistrationsRoute: typeof AdminTournamentsTournamentIdRegistrationsRoute
  AdminTournamentsTournamentIdSettingsRoute: typeof AdminTournamentsTournamentIdSettingsRoute
  AdminTournamentsTournamentIdStandingsRoute: typeof AdminTournamentsTournamentIdStandingsRoute
  AdminTournamentsTournamentIdTimerRoute: typeof AdminTournamentsTournamentIdTimerRoute
  AdminTournamentsTournamentIdIndexRoute: typeof AdminTournamentsTournamentIdIndexRoute
}

const AdminTournamentsTournamentIdRouteChildren: AdminTournamentsTournamentIdRouteChildren =
  {
    AdminTournamentsTournamentIdLogRoute: AdminTournamentsTournamentIdLogRoute,
    AdminTournamentsTournamentIdPairingsRoute:
      AdminTournamentsTournamentIdPairingsRoute,
    AdminTournamentsTournamentIdRegistrationsRoute:
      AdminTournamentsTournamentIdRegistrationsRoute,
    AdminTournamentsTournamentIdSettingsRoute:
      AdminTournamentsTournamentIdSettingsRoute,
    AdminTournamentsTournamentIdStandingsRoute:
      AdminTournamentsTournamentIdStandingsRoute,
    AdminTournamentsTournamentIdTimerRoute:
      AdminTournamentsTournamentIdTimerRoute,
    AdminTournamentsTournamentIdIndexRoute:
      AdminTournamentsTournamentIdIndexRoute,
  }

const AdminTournamentsTournamentIdRouteWithChildren =
  AdminTournamentsTournamentIdRoute._addFileChildren(
    AdminTournamentsTournamentIdRouteChildren,
  )

interface AdminRouteChildren {
  AdminOrganizationRoute: typeof AdminOrganizationRoute
  AdminStaffRoute: typeof AdminStaffRoute
  AdminStripeReturnRoute: typeof AdminStripeReturnRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminConventionsConventionIdRoute: typeof AdminConventionsConventionIdRouteWithChildren
  AdminTournamentsTournamentIdRoute: typeof AdminTournamentsTournamentIdRouteWithChildren
  AdminConventionsIndexRoute: typeof AdminConventionsIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminOrganizationRoute: AdminOrganizationRoute,
  AdminStaffRoute: AdminStaffRoute,
  AdminStripeReturnRoute: AdminStripeReturnRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminConventionsConventionIdRoute:
    AdminConventionsConventionIdRouteWithChildren,
  AdminTournamentsTournamentIdRoute:
    AdminTournamentsTournamentIdRouteWithChildren,
  AdminConventionsIndexRoute: AdminConventionsIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  SettingsRoute: SettingsRoute,
  JoinInviteCodeRoute: JoinInviteCodeRoute,
  SignInSplatRoute: SignInSplatRoute,
  SignUpSplatRoute: SignUpSplatRoute,
  UsersPublicCodeRoute: UsersPublicCodeRoute,
  ConventionsConventionIdPaymentRoute: ConventionsConventionIdPaymentRoute,
  TournamentsTournamentIdDecklistRoute: TournamentsTournamentIdDecklistRoute,
  TournamentsTournamentIdPaymentRoute: TournamentsTournamentIdPaymentRoute,
  TournamentsTournamentIdPlayRoute: TournamentsTournamentIdPlayRoute,
  ConventionsConventionIdIndexRoute: ConventionsConventionIdIndexRoute,
  TournamentsTournamentIdIndexRoute: TournamentsTournamentIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
