#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets these two at the top of the stages section.
TOTAL_STAGES=0
TOTAL_MINUTES=0

_STAGE_INDEX=0
_MINUTES_ELAPSED=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does and how long it takes.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages · about %s minutes%s\n\n' \
    "$DIM" "$TOTAL_STAGES" "$TOTAL_MINUTES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" <minutes> — clear the screen, then announce a stage and show
# progress + time remaining. Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  local remaining=$((TOTAL_MINUTES - _MINUTES_ELAPSED))
  (( remaining < 0 )) && remaining=0
  _MINUTES_ELAPSED=$((_MINUTES_ELAPSED + ${2:-0}))
  printf '\n%s%s▸ Stage %s/%s · %s%s  %s(~%s min left)%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET" "$DIM" "$remaining" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set the two totals to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
REPO_ROOT=$(cd "$SCRIPT_DIR/.." && pwd)
WEB_ENV="$REPO_ROOT/apps/web/.env.local"
NATIVE_ENV="$REPO_ROOT/apps/native/.env.local"

TOTAL_STAGES=6
TOTAL_MINUTES=15

banner "Sentry error monitoring — tournament-os"

# ── Stage 1: web project ──────────────────────────────────────────────────
stage "Sentry — organization and web project" 3
say "The code on this branch reports errors as soon as DSNs exist; this"
say "wizard creates the Sentry projects and captures those DSNs."
open_url "https://sentry.io/"
step "Sign in (or create a free account and organization)."
step "Go to Projects → Create Project."
step "Platform: React. Name it e.g. 'tournament-os-web'. Create it."
step "Copy the DSN from the setup page (or later: Settings → Projects →"
step "  tournament-os-web → Client Keys (DSN))."
ENV_FILE="$WEB_ENV"
ask SENTRY_PROJECT_WEB "Web project slug (e.g. tournament-os-web):"
ask VITE_SENTRY_DSN "Paste the web DSN (https://...ingest...):"
write_env VITE_SENTRY_DSN "$VITE_SENTRY_DSN"
note "The web app (client + SSR) reads VITE_SENTRY_DSN at build time."

# ── Stage 2: native project ───────────────────────────────────────────────
stage "Sentry — native (Expo) project" 2
open_url "https://sentry.io/"
step "Projects → Create Project again."
step "Platform: React Native. Name it e.g. 'tournament-os-native'."
step "Copy this project's DSN."
ENV_FILE="$NATIVE_ENV"
ask SENTRY_PROJECT_NATIVE "Native project slug (e.g. tournament-os-native):"
ask EXPO_PUBLIC_SENTRY_DSN "Paste the native DSN:"
write_env EXPO_PUBLIC_SENTRY_DSN "$EXPO_PUBLIC_SENTRY_DSN"
note "apps/native reads EXPO_PUBLIC_SENTRY_DSN in src/app/_layout.tsx."

# ── Stage 3: source-map credentials ───────────────────────────────────────
stage "Sentry — auth token for source-map upload" 3
say "Production stack traces stay readable only if builds upload source"
say "maps. That needs an org auth token plus the org/project slugs."
open_url "https://sentry.io/settings/auth-tokens/"
step "Create a new Organization Auth Token (default scopes are fine)."
step "Copy the token (starts 'sntrys_')."
ENV_FILE="$WEB_ENV"
ask SENTRY_ORG "Your Sentry organization slug (from the URL):"
ask_secret SENTRY_AUTH_TOKEN "Paste the auth token:"
write_env SENTRY_ORG "$SENTRY_ORG"
write_env SENTRY_PROJECT "$SENTRY_PROJECT_WEB"
write_env SENTRY_AUTH_TOKEN "$SENTRY_AUTH_TOKEN"
ENV_FILE="$NATIVE_ENV"
write_env SENTRY_ORG "$SENTRY_ORG"
write_env SENTRY_PROJECT "$SENTRY_PROJECT_NATIVE"
write_env SENTRY_AUTH_TOKEN "$SENTRY_AUTH_TOKEN"
note "Web: vite.config.ts enables upload only when SENTRY_AUTH_TOKEN is set."
note "Native: the @sentry/react-native Expo plugin reads these during native"
note "builds. For EAS builds, add the same three values as EAS env vars"
note "(SENTRY_AUTH_TOKEN with 'sensitive' visibility)."

# ── Stage 4: Convex exception reporting ───────────────────────────────────
stage "Convex — exception reporting (needs Convex Pro)" 3
say "Convex reports function exceptions to Sentry via a dashboard-side"
say "integration — no code involved. It is only available on Convex Pro."
if confirm "Is this Convex team on the Pro plan (or upgrading now)?"; then
  open_url "https://sentry.io/"
  step "Create one more Sentry project. Platform: Node.js. Name it e.g."
  step "  'tournament-os-convex' and copy its DSN."
  open_url "https://dashboard.convex.dev/"
  step "Open the tournament-os project → your deployment → Settings →"
  step "  Integrations → Exception Reporting → Sentry."
  step "Paste the Node.js project DSN and save."
  note "Repeat for the prod deployment when one exists — the integration is"
  note "configured per deployment."
  pause "Done configuring the Convex integration?"
else
  SKIPPED+=("Convex exception reporting — requires Convex Pro; re-run this wizard after upgrading")
  warn "Skipping — Convex function errors stay dashboard-logs-only for now."
fi

# ── Stage 5: Vercel production env vars ───────────────────────────────────
stage "Vercel — production environment variables" 2
say "Production web builds need the same values Vercel-side."
warn "Note: the Vercel build boundary is still broken (separate TODO), so"
warn "deploys may not succeed yet regardless of these variables."
if confirm "Add the Sentry variables to Vercel now?"; then
  open_url "https://vercel.com/dashboard"
  step "Open the tournament-os web project → Settings → Environment Variables."
  step "Add: VITE_SENTRY_DSN, SENTRY_ORG, SENTRY_PROJECT (web slug), and"
  step "  SENTRY_AUTH_TOKEN (mark it Sensitive)."
  pause "Done adding them?"
else
  SKIPPED+=("Vercel env vars: VITE_SENTRY_DSN, SENTRY_ORG, SENTRY_PROJECT, SENTRY_AUTH_TOKEN")
fi

# ── Stage 6: verify ───────────────────────────────────────────────────────
stage "Verify an event reaches Sentry" 2
say "From the repo root, in another terminal:"
say ""
say "    pnpm --filter @tournament-os/web dev"
say ""
step "Open http://localhost:3000, open the browser devtools console, run:"
say ""
say "    setTimeout(() => { throw new Error('sentry-wizard-test') })"
say ""
step "Then check the web project's Issues feed in Sentry — the event"
step "  usually appears within a minute."
open_url "https://sentry.io/issues/"
note "Native: JS errors report from a dev build (expo run:ios/android)."
note "Native-crash reporting needs a rebuild since the Sentry plugin was"
note "added — Expo Go cannot load the native module."
pause "See the test event?"

finish
