/// <reference types="vite/client" />

// Organizer pairing edits (model/manualPairing.ts): breaking a generated
// pairing and manually re-pairing the freed players — against each other or
// as a Bye — while the round's pairings are still organizer-only. Publishing
// (and completing, which publishes) is blocked while any active player is
// left without a pairing.

import { expect, test } from "vitest";

import { api } from "./_generated/api";
import type { Id } from "./_generated/dataModel";
import { organizerIdentity, seedTournamentWithPlayers } from "./specHelpers";
import { createConvexTest } from "./specHelpers.runtime";

type Test = ReturnType<typeof createConvexTest>;

// A four-player Swiss event whose round-one pairings are organizer-only
// (autoPublishPairings off), started and ready for pairing edits.
async function seedUnpublishedRoundOne(
  t: Test,
  options?: { playerCount?: number },
) {
  const { tournamentId, registrationIds } = await seedTournamentWithPlayers(t, {
    name: "Manual Pairing Event",
    playerCount: options?.playerCount ?? 4,
    autoPublishPairings: false,
    playerNames: true,
    phases: [{ phaseOrder: 1, phaseRoundMode: "fixed", phaseTotalRounds: 2 }],
  });
  const organizer = t.withIdentity(organizerIdentity);
  const roundId = await organizer.mutation(
    api.tournaments.rounds.startTournament,
    { tournamentId },
  );
  return { organizer, tournamentId, registrationIds, roundId };
}

async function pairings(
  organizer: ReturnType<Test["withIdentity"]>,
  roundId: Id<"tournamentRounds">,
) {
  return await organizer.query(api.tournaments.rounds.listRoundPairings, {
    roundId,
  });
}

test("breaking a pairing frees its players and blocks publish until re-paired", async () => {
  const t = createConvexTest();
  const { organizer, tournamentId, roundId } = await seedUnpublishedRoundOne(t);

  const before = await pairings(organizer, roundId);
  expect(before).toHaveLength(2);
  const broken = before[0];
  await organizer.mutation(api.tournaments.rounds.breakPairing, {
    matchId: broken.match._id,
  });

  const freed = await organizer.query(
    api.tournaments.rounds.listUnpairedPlayers,
    { roundId },
  );
  expect(new Set(freed.map((player) => player.registrationId))).toEqual(
    new Set(broken.players.map((player) => player.playerId)),
  );

  // The publish gate holds on both the mutation and the board's next step.
  await expect(
    organizer.mutation(api.tournaments.rounds.publishPairings, { roundId }),
  ).rejects.toThrow("Every active player needs an opponent or a bye");
  const blockedBoard = await organizer.query(
    api.tournaments.rounds.getPairingsBoard,
    { tournamentId },
  );
  expect(blockedBoard.nextStep).toEqual({
    kind: "publishPairings",
    ready: false,
    reason: "2 players need an opponent or a bye",
    roundId,
  });

  // Re-pairing the freed players takes a fresh table number — broken
  // pairings never hand their table to a new match.
  await organizer.mutation(api.tournaments.rounds.pairPlayers, {
    roundId,
    playerOneRegistrationId: freed[0].registrationId,
    playerTwoRegistrationId: freed[1].registrationId,
  });
  const after = await pairings(organizer, roundId);
  expect(after).toHaveLength(2);
  expect(after.map(({ match }) => match.tableNumber).sort()).toEqual([2, 3]);
  expect(
    await organizer.query(api.tournaments.rounds.listUnpairedPlayers, {
      roundId,
    }),
  ).toEqual([]);

  const readyBoard = await organizer.query(
    api.tournaments.rounds.getPairingsBoard,
    { tournamentId },
  );
  expect(readyBoard.nextStep).toEqual({
    kind: "publishPairings",
    ready: true,
    reason: null,
    roundId,
  });
  await organizer.mutation(api.tournaments.rounds.publishPairings, {
    roundId,
  });

  // Both edits are on the audit trail.
  const events = await organizer.query(
    api.tournaments.auditLog.listAuditEvents,
    { tournamentId, paginationOpts: { numItems: 20, cursor: null } },
  );
  const kinds = events.page.map((row) => row.event.type);
  expect(kinds).toContain("pairing_broken");
  expect(kinds).toContain("pairing_created");
});

test("manual byes cover freed players and score like generated byes", async () => {
  const t = createConvexTest();
  const { organizer, roundId } = await seedUnpublishedRoundOne(t);

  const before = await pairings(organizer, roundId);
  const broken = before[0];
  const kept = before[1];
  await organizer.mutation(api.tournaments.rounds.breakPairing, {
    matchId: broken.match._id,
  });
  for (const player of broken.players) {
    await organizer.mutation(api.tournaments.rounds.assignBye, {
      roundId,
      registrationId: player.playerId,
    });
  }
  await organizer.mutation(api.tournaments.rounds.publishPairings, {
    roundId,
  });
  await organizer.mutation(api.tournaments.rounds.recordMatchResult, {
    matchId: kept.match._id,
    playerOneRegistrationId: kept.players[0].playerId,
    playerTwoRegistrationId: kept.players[1].playerId,
    playerOneGameWins: 2,
    playerTwoGameWins: 0,
  });
  await organizer.mutation(api.tournaments.rounds.completeRound, { roundId });

  const standings = await organizer.query(
    api.tournaments.rounds.listRoundStandings,
    { roundId },
  );
  const byePlayerIds = new Set(broken.players.map((player) => player.playerId));
  const byeRows = standings.filter(({ standing }) =>
    byePlayerIds.has(standing.playerId),
  );
  expect(byeRows).toHaveLength(2);
  for (const { standing } of byeRows) {
    expect(standing.matchPoints).toBe(3);
  }
});

test("breaking a bye deletes its awarded result with the match", async () => {
  const t = createConvexTest();
  const { organizer, roundId } = await seedUnpublishedRoundOne(t, {
    playerCount: 5,
  });

  const byePairing = (await pairings(organizer, roundId)).find(({ players }) =>
    players.some((player) => player.isBye),
  );
  expect(byePairing).toBeDefined();
  await organizer.mutation(api.tournaments.rounds.breakPairing, {
    matchId: byePairing!.match._id,
  });

  await t.run(async (ctx) => {
    expect(await ctx.db.get(byePairing!.match._id)).toBeNull();
    const revisions = await ctx.db
      .query("matchResultRevisions")
      .withIndex("by_tournamentMatchId", (q) =>
        q.eq("tournamentMatchId", byePairing!.match._id),
      )
      .collect();
    expect(revisions).toEqual([]);
  });

  // The freed player can be re-awarded the bye by hand.
  const freed = await organizer.query(
    api.tournaments.rounds.listUnpairedPlayers,
    { roundId },
  );
  expect(freed).toHaveLength(1);
  await organizer.mutation(api.tournaments.rounds.assignBye, {
    roundId,
    registrationId: freed[0].registrationId,
  });
  await organizer.mutation(api.tournaments.rounds.publishPairings, {
    roundId,
  });
});

test("pairing edits are refused once pairings are published", async () => {
  const t = createConvexTest();
  const { organizer, roundId } = await seedUnpublishedRoundOne(t);
  await organizer.mutation(api.tournaments.rounds.publishPairings, {
    roundId,
  });

  const [pairing] = await pairings(organizer, roundId);
  await expect(
    organizer.mutation(api.tournaments.rounds.breakPairing, {
      matchId: pairing.match._id,
    }),
  ).rejects.toThrow("no longer be edited after they are published");
  await expect(
    organizer.mutation(api.tournaments.rounds.assignBye, {
      roundId,
      registrationId: pairing.players[0].playerId,
    }),
  ).rejects.toThrow("no longer be edited after they are published");
});

test("a pairing with an entered result cannot be broken", async () => {
  const t = createConvexTest();
  const { organizer, roundId } = await seedUnpublishedRoundOne(t);

  const [pairing] = await pairings(organizer, roundId);
  await organizer.mutation(api.tournaments.rounds.recordMatchResult, {
    matchId: pairing.match._id,
    playerOneRegistrationId: pairing.players[0].playerId,
    playerTwoRegistrationId: pairing.players[1].playerId,
    playerOneGameWins: 2,
    playerTwoGameWins: 1,
  });
  await expect(
    organizer.mutation(api.tournaments.rounds.breakPairing, {
      matchId: pairing.match._id,
    }),
  ).rejects.toThrow("recorded result cannot be broken");
});

test("a conceded pairing can be broken, and a dropped player never blocks publish", async () => {
  const t = createConvexTest();
  const { organizer, roundId } = await seedUnpublishedRoundOne(t);

  // Dropping a paired player pre-publish concedes their match — an
  // automatic result, so the pairing can still be broken (same rule as
  // Rewind: nothing anyone entered is destroyed).
  const [pairing] = await pairings(organizer, roundId);
  const dropped = pairing.players[0];
  await organizer.mutation(api.tournaments.registrations.dropRegistration, {
    registrationId: dropped.playerId,
  });
  await organizer.mutation(api.tournaments.rounds.breakPairing, {
    matchId: pairing.match._id,
  });

  // Only the surviving opponent needs a new pairing: the dropped player is
  // no longer active, so the publish gate ignores them.
  const freed = await organizer.query(
    api.tournaments.rounds.listUnpairedPlayers,
    { roundId },
  );
  expect(freed.map((player) => player.registrationId)).toEqual([
    pairing.players[1].playerId,
  ]);
  await expect(
    organizer.mutation(api.tournaments.rounds.publishPairings, { roundId }),
  ).rejects.toThrow("Every active player needs an opponent or a bye");
  await organizer.mutation(api.tournaments.rounds.assignBye, {
    roundId,
    registrationId: pairing.players[1].playerId,
  });
  await organizer.mutation(api.tournaments.rounds.publishPairings, {
    roundId,
  });
});

test("manual pairing rejects inactive, already-paired, and self pairings", async () => {
  const t = createConvexTest();
  const { organizer, roundId } = await seedUnpublishedRoundOne(t);

  const [broken, kept] = await pairings(organizer, roundId);
  await organizer.mutation(api.tournaments.rounds.breakPairing, {
    matchId: broken.match._id,
  });
  const [freedOne, freedTwo] = broken.players;
  await organizer.mutation(api.tournaments.registrations.dropRegistration, {
    registrationId: freedTwo.playerId,
  });

  await expect(
    organizer.mutation(api.tournaments.rounds.pairPlayers, {
      roundId,
      playerOneRegistrationId: freedOne.playerId,
      playerTwoRegistrationId: freedTwo.playerId,
    }),
  ).rejects.toThrow("not active in this tournament");
  await expect(
    organizer.mutation(api.tournaments.rounds.pairPlayers, {
      roundId,
      playerOneRegistrationId: freedOne.playerId,
      playerTwoRegistrationId: kept.players[0].playerId,
    }),
  ).rejects.toThrow("already paired in this round");
  await expect(
    organizer.mutation(api.tournaments.rounds.pairPlayers, {
      roundId,
      playerOneRegistrationId: freedOne.playerId,
      playerTwoRegistrationId: freedOne.playerId,
    }),
  ).rejects.toThrow("cannot be paired against themself");
  await expect(
    organizer.mutation(api.tournaments.rounds.assignBye, {
      roundId,
      registrationId: freedTwo.playerId,
    }),
  ).rejects.toThrow("not active in this tournament");
});

test("completing an unpublished round is blocked while a player is unpaired", async () => {
  const t = createConvexTest();
  const { organizer, roundId } = await seedUnpublishedRoundOne(t);

  const [broken, kept] = await pairings(organizer, roundId);
  await organizer.mutation(api.tournaments.rounds.breakPairing, {
    matchId: broken.match._id,
  });
  await organizer.mutation(api.tournaments.rounds.recordMatchResult, {
    matchId: kept.match._id,
    playerOneRegistrationId: kept.players[0].playerId,
    playerTwoRegistrationId: kept.players[1].playerId,
    playerOneGameWins: 2,
    playerTwoGameWins: 0,
  });

  // Completing publishes the pairings as part of the round's record, so it
  // honors the same all-players-paired gate as publishing.
  await expect(
    organizer.mutation(api.tournaments.rounds.completeRound, { roundId }),
  ).rejects.toThrow("Every active player needs an opponent or a bye");

  await organizer.mutation(api.tournaments.rounds.pairPlayers, {
    roundId,
    playerOneRegistrationId: broken.players[0].playerId,
    playerTwoRegistrationId: broken.players[1].playerId,
  });
  const repaired = (await pairings(organizer, roundId)).find(
    ({ match }) => match.tableNumber === 3,
  );
  await organizer.mutation(api.tournaments.rounds.recordMatchResult, {
    matchId: repaired!.match._id,
    playerOneRegistrationId: repaired!.players[0].playerId,
    playerTwoRegistrationId: repaired!.players[1].playerId,
    playerOneGameWins: 2,
    playerTwoGameWins: 1,
  });
  await organizer.mutation(api.tournaments.rounds.completeRound, { roundId });
});

test("bracket pairings cannot be edited", async () => {
  const t = createConvexTest();
  const { tournamentId } = await seedTournamentWithPlayers(t, {
    name: "Bracket Edit Refusal",
    playerCount: 4,
    autoPublishPairings: false,
    phases: [
      {
        phaseOrder: 1,
        phaseType: "single_elimination",
        phaseRoundMode: "dynamic",
      },
    ],
  });
  const organizer = t.withIdentity(organizerIdentity);
  const roundId = await organizer.mutation(
    api.tournaments.rounds.startTournament,
    { tournamentId },
  );

  const [pairing] = await pairings(organizer, roundId);
  await expect(
    organizer.mutation(api.tournaments.rounds.breakPairing, {
      matchId: pairing.match._id,
    }),
  ).rejects.toThrow("Bracket pairings are set by seeding");
});
